### ISSUE TITLE
我想推送更新的代码,可以给我权限吗

### ISSUE THREAD

**Issue by wwhyes** [kevyu/weui-sass#14]
我的版本：https://github.com/wwhyes/weui-sass
1.同步weui官网demo；
2.新增首页4个图标和1个文章图片；
3.将gulp配置中的gulp-minify-css修改为gulp-clean-css;
4.新增命名空间${ns}:weui-(这部分我还没全修复，可以的话更方便项目使用)；
5.修复weui_media_box中sass不支持Changing Selector Order语法；
6.修复weui_btn_title中被忽视的margin_bottom;
PS：
1.这个UI公司项目也在用，所以我也想出份力啊！
2.关于命名空间如果您同意的话，那我就大胆将所有weui_改成#{ns}了啊，栗子:weui_media_box.scss
3.还有一个问题就是那个hashchange只能翻一次页呢，所以tab那个页面就有点尴尬了

**Comment by kevyu** [comment]
直接提交pull request就可以了。

**Comment by wwhyes** [comment]
好了

**Comment by Eric-Guo** [comment]
看到你的PR了，感谢贡献，我暂时关掉这个issue了，后续讨论可以在#15 上进行。
